dist: trusty

language: android

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.3

    # The SDK version used to compile your project
    - android-29

before_install:
  - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64
  - sudo install bazelisk-linux-amd64 /usr/local/bin/bazel

script:
  - # Test the maven integration's internal unit tests
  - bazel test //...
  - # Exercise the kramer tool.
  - (cd kramer && bazel build //...)
  - (cd kramer && bazel test //...)
  - # Exercise the sample project.
  - (cd test/test_workspace && bazel build //...)
  - (cd test/test_workspace && bazel test //...)
