language: generic
dist: xenial
sudo: enabled
os:
  - osx
  - linux

env:
  global:
    - ANDROID_HOME=${HOME}/android-sdk
    - ANDROID_SDK_TOOLS_VERSION=4333796
    - ANDROID_BUILD_TOOLS_VERSION="28.0.3"
    - ANDROID_PLATFORM_VERSION=28
    - BAZELISK_VERSION="0.0.8"
    - PATH=${PATH}:${ANDROID_HOME}/tools/bin:${HOME}/bin
  matrix:
    - USE_BAZEL_VERSION="0.29.0" SEGMENT="."
    - USE_BAZEL_VERSION="0.29.0" SEGMENT="test/test_workspace"

addons:
  apt:
    packages:
      - wget
      - openjdk-8-jdk
  homebrew:
    taps:
      - adoptopenjdk/openjdk
    casks:
      - adoptopenjdk8
    update: true

before_install:
  - if [ "osx" == "${TRAVIS_OS_NAME}" ]; then export PLATFORM="darwin" ; else export PLATFORM="${TRAVIS_OS_NAME}" ; fi
  - if [ "osx" == "${TRAVIS_OS_NAME}" ]; then export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home" ; fi
  - if [ "linux" == "${TRAVIS_OS_NAME}" ]; then export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64" ; fi
  - ls -FaCl ${JAVA_HOME}/bin

install:
  - tools/install_android_studio.sh
  - tools/install_bazelisk.sh
  - java -version
  - bazel version

script:
  - # Test each root in the build matrix.
  - cd ${HOME}/build/${TRAVIS_REPO_SLUG}/${SEGMENT}
  - bazel test //...

cache:
  directories:
    - $HOME/.cache/bazel_maven_repository
    - $HOME/bin
    - $HOME/android-sdk
