dist: trusty

language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64
  - sudo install bazelisk-linux-amd64 /usr/local/bin/bazel

script:
  - # Test the maven integration's internal unit tests
  - bazel test //...
  - # Exercise the sample project.
  - cd test/test_workspace
  - bazel test //...
